apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: DS_ANALYZER_POSTGRESQL
    access: proxy
    url: postgres:5432
    database: analyzer_metrics
    user: analyzer_user
    secureJsonData:
      password: analyzer_password
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true 